@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NGQ4NDM4NTAxZjBlMTJmYmYyNWJmYSIsImlhdCI6MTc2NjY5MTQ4MywiZXhwIjoxNzY3Mjk2MjgzfQ.dOEmz5SKl7lbO5pn1DxKw-5C3ARKR_nDmJrsxYVFfgQ
### Health check
GET http://localhost:3000/health

### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Sude",
  "email": "sude@test.com",
  "password": "123456"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "sude@test.com",
  "password": "123456"
}

### Get current user
GET http://localhost:3000/api/users/me
Authorization: Bearer {{token}}

### Add item
POST http://localhost:3000/api/pantry
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Milk",
  "quantity": 2,
  "category": "Dairy",
  "expirationDate": "2025-01-02"
}

### Add item
POST http://localhost:3000/api/pantry
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Cheese",
  "quantity": 3,
  "category": "Dairy",
  "expirationDate": "2025-01-02"
}

### Add item
POST http://localhost:3000/api/pantry
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Broccoli",
  "quantity": 1,
  "category": "Vegetable",
  "expirationDate": "2025-01-01"
}

### List items
GET http://localhost:3000/api/pantry
Authorization: Bearer {{token}}

### Get item by ID
GET http://localhost:3000/api/pantry/694d8cb3a0c9993abd53e80d
Authorization: Bearer {{token}}

### Update item
PUT http://localhost:3000/api/pantry/694d8d6aa0c9993abd53e815
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "expirationDate": "2025-12-28"
}

### Delete item
DELETE http://localhost:3000/api/pantry/694d8d30a0c9993abd53e812
Authorization: Bearer {{token}}

### Get expiring items
GET http://localhost:3000/api/pantry/expiring
Authorization: Bearer {{token}}

### Search by name
GET http://localhost:3000/api/pantry/search?name=miL
Authorization: Bearer {{token}}

### Filter by category
GET http://localhost:3000/api/pantry/category/Vegetable
Authorization: Bearer {{token}}

### Get summary
GET http://localhost:3000/api/reports/summary
Authorization: Bearer {{token}}

### Add to shopping list
POST http://localhost:3000/api/shopping-list
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Eggs",
  "quantity": 6
}

### Add to shopping list
POST http://localhost:3000/api/shopping-list
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Bacon",
  "quantity": 12
}

### View shopping list
GET http://localhost:3000/api/shopping-list
Authorization: Bearer {{token}}

### Remove item from shopping list
DELETE http://localhost:3000/api/shopping-list/694d99fe7757000ae75433be
Authorization: Bearer {{token}}

